// tslint:disable
// eslint-disable
/**
 * Hedwig API test
 * Prototype of REST API for Hedwig client 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Enrollment,
    EnrollmentFromJSON,
    EnrollmentToJSON,
    User,
    UserFromJSON,
    UserToJSON,
} from '../models';

export interface OrganizationsOrganizationIdSitesSiteIdEnrollmentsGetRequest {
    organizationId: number;
    siteId: number;
    include?: Array<string>;
}

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Return all enrollments at a site
     */
    async organizationsOrganizationIdSitesSiteIdEnrollmentsGetRaw(requestParameters: OrganizationsOrganizationIdSitesSiteIdEnrollmentsGetRequest): Promise<runtime.ApiResponse<Array<Enrollment>>> {
        if (requestParameters.organizationId === null || requestParameters.organizationId === undefined) {
            throw new runtime.RequiredError('organizationId','Required parameter requestParameters.organizationId was null or undefined when calling organizationsOrganizationIdSitesSiteIdEnrollmentsGet.');
        }

        if (requestParameters.siteId === null || requestParameters.siteId === undefined) {
            throw new runtime.RequiredError('siteId','Required parameter requestParameters.siteId was null or undefined when calling organizationsOrganizationIdSitesSiteIdEnrollmentsGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.include) {
            queryParameters['include[]'] = requestParameters.include;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{organizationId}/sites/{siteId}/enrollments`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters.organizationId))).replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters.siteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EnrollmentFromJSON));
    }

    /**
     * Return all enrollments at a site
     */
    async organizationsOrganizationIdSitesSiteIdEnrollmentsGet(requestParameters: OrganizationsOrganizationIdSitesSiteIdEnrollmentsGetRequest): Promise<Array<Enrollment>> {
        const response = await this.organizationsOrganizationIdSitesSiteIdEnrollmentsGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get user info for currently authed user
     */
    async usersCurrentGetRaw(): Promise<runtime.ApiResponse<User>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/current`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Get user info for currently authed user
     */
    async usersCurrentGet(): Promise<User> {
        const response = await this.usersCurrentGetRaw();
        return await response.value();
    }

}
