version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: TestPassword1
      ACCEPT_EULA: Y
  backend:
    container_name: backend
    build:
        context: .
        dockerfile: Dockerfile-backend
    environment:
      DB_TYPE: SqlServer
      SQLCONNSTR_HEDWIG: Server=db;Database=master;User=sa;Password=TestPassword1
      CLIENT_HOST: 'http://client:3000'
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: 1
    volumes:
      - ./src/Hedwig:/app/src/Hedwig
      - ./test/HedwigTests:/app/src/HedwigTests
      # These two volume statements are necessary if you are using a Windows Machine
      # This probably means you won't be able to debug using VSC
      - /app/src/Hedwig/obj
      - /app/src/Hedwig/bin
      - /app/test/HedwigTests/obj
      - /app/test/HedwigTests/bin
      - ./entrypoint-backend.sh:/entrypoint.sh
    working_dir: /app/src/Hedwig
    ports:
      - 5001:5001
      - 5000:5000
    entrypoint:
      - sh
      - /entrypoint.sh
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    volumes:
      - ./src/Hedwig/ClientApp:/home/node/mapped-app
      - ./src/Hedwig/ClientApp/node_modules:/home/node/app/node_modules
      - ./entrypoint-client.sh:/entrypoint.sh
    working_dir: /home/node/app
    environment:
      - DOCKER_ON_WINDOWS=true
    ports:
      - 3000:3000
    entrypoint:
      - sh
      - /entrypoint.sh
    depends_on:
      - backend
