version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: TestPassword1
      ACCEPT_EULA: Y
  backend:
    container_name: backend
    build:
        context: ./
        dockerfile: Dockerfile-dev
    environment:
      DB_TYPE: SqlServer
      SQLCONNSTR_HEDWIG: Server=db;Database=master;User=sa;Password=TestPassword1
      CLIENT_HOST: 'http://client:3000'
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - .:/app
      # These two volume statements are necessary if you are using a Windows Machine
      # This probably means you won't be able to debug using VSC
      - /app/obj
      - /app/bin
    working_dir: /app
    ports:
      - 5001:5001
      - 5000:5000
    entrypoint:
      - sh
      - /app/entrypoint.sh
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: ./ClientApp/Dockerfile-dev
    volumes:
      - ./ClientApp:/home/node/mapped-app
      - ./ClientApp/node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    environment:
      - DOCKER_ON_WINDOWS=true
    ports:
      - 3000:3000
    entrypoint:
      - sh
      - /home/node/mapped-app/entrypoint.sh
    depends_on:
      - backend
