import { Age, FundingTime, Region } from '../../../generated';

export const CdcRates = [
  {
    "accredited": false,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 148.73,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 52.1,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 126.59,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 44.2,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 99.05,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 47.95,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 148.73,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 52.1,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 126.59,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 44.2,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 99.75,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 48.48,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 148.73,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 52.1,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 126.59,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 44.2,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 102.03,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 49.44,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 153.16,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 53.5,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 126.59,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 44.2,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 99.05,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 47.95,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 179.43,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 62.7,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 126.59,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 44.2,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 105.7,
  },
  {
    "accredited": false,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 51.28,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 167.38,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 58.5,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 126.59,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 44.2,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 110.34,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 53.46,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 167.38,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 58.5,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 126.59,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 44.2,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 111.3,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 53.99,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 167.38,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 58.5,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 126.59,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 44.2,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 113.75,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 55.13,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 172.32,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 60.3,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 126.59,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 44.2,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 110.34,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 53.46,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 201.67,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 70.5,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 126.59,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 44.2,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 118.13,
  },
  {
    "accredited": false,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 57.23,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 169.95,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 59.5,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 165.32,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 57.85,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 113.2,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.East,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 54.8,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 169.95,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 59.5,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 165.32,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 57.85,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 114,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 55.4,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 169.95,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 59.5,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 165.32,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 57.85,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 116.6,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.NorthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 56.5,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 175,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 61.1,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 165.32,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 57.85,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 113.2,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 54.8,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 205.07,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 71.8,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 165.32,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 57.85,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 120.8,
  },
  {
    "accredited": true,
    "titleI": false,
    "region": Region.SouthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 58.6,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 191.27,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 66.8,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 165.32,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 57.85,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 126.1,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.East,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 61.1,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 191.27,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 66.8,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 165.32,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 57.85,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 127.2,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 61.7,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 191.27,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 66.8,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 165.32,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 57.85,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 130,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.NorthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 63,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 196.94,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 68.9,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 165.32,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 57.85,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 126.1,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthCentral,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 61.1,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Full,
    "rate": 230.51,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.InfantToddler,
    "time": FundingTime.Part,
    "rate": 80.5,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Full,
    "rate": 165.32,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.Preschool,
    "time": FundingTime.Part,
    "rate": 57.85,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Full,
    "rate": 135,
  },
  {
    "accredited": true,
    "titleI": true,
    "region": Region.SouthWest,
    "ageGroup": Age.SchoolAge,
    "time": FundingTime.Part,
    "rate": 65.4,
  },
];
