// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Hedwig.Data;

namespace Hedwig.Migrations
{
	[DbContext(typeof(HedwigContext))]
	partial class HedwigContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
	                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
	                .HasAnnotation("Relational:MaxIdentifierLength", 128)
	                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("hedwig.Models.Child", b =>
					{
						b.Property<Guid>("Id")
											.ValueGeneratedOnAdd();

						b.Property<bool?>("AmericanIndianOrAlaskaNative");

						b.Property<bool?>("Asian");

						b.Property<DateTime>("Birthdate");

						b.Property<bool?>("BlackOrAfricanAmerican");

						b.Property<int?>("FamilyId");

						b.Property<string>("FirstName")
											.IsRequired()
											.HasMaxLength(35);

						b.Property<int>("Gender");

						b.Property<bool?>("HispanicOrLatinxEthnicity");

						b.Property<string>("LastName")
											.IsRequired()
											.HasMaxLength(35);

						b.Property<string>("MiddleName")
											.HasMaxLength(35);

						b.Property<bool?>("NativeHawaiianOrPacificIslander");

						b.Property<string>("Suffix")
											.HasMaxLength(10);

						b.Property<bool?>("White");

						b.HasKey("Id");

						b.HasIndex("FamilyId");

						b.ToTable("Child");
					});

			modelBuilder.Entity("hedwig.Models.Enrollment", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd();

						b.Property<Guid>("ChildId");

						b.Property<DateTime>("Entry");

						b.Property<DateTime?>("Exit");

						b.Property<int>("SiteId");

						b.HasKey("Id");

						b.HasIndex("ChildId");

						b.HasIndex("SiteId");

						b.ToTable("Enrollment");
					});

			modelBuilder.Entity("hedwig.Models.Family", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd();

						b.HasKey("Id");

						b.ToTable("Family");
					});

			modelBuilder.Entity("hedwig.Models.FamilyDetermination", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd();

						b.Property<DateTime>("Determined");

						b.Property<int>("FamilyId");

						b.Property<decimal>("Income");

						b.Property<int>("NumberOfPeople");

						b.HasKey("Id");

						b.HasIndex("FamilyId");

						b.ToTable("FamilyDetermination");
					});

			modelBuilder.Entity("hedwig.Models.Funding", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd();

						b.Property<int>("EnrollmentId");

						b.Property<DateTime>("Entry");

						b.Property<DateTime?>("Exit");

						b.Property<int>("Source");

						b.HasKey("Id");

						b.HasIndex("EnrollmentId");

						b.ToTable("Funding");
					});

			modelBuilder.Entity("hedwig.Models.Site", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd();

						b.Property<string>("Name")
											.IsRequired()
											.HasMaxLength(100);

						b.HasKey("Id");

						b.ToTable("Site");
					});

			modelBuilder.Entity("hedwig.Models.SitePermission", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd();

						b.Property<int>("SiteId");

						b.Property<int>("UserId");

						b.HasKey("Id");

						b.HasIndex("SiteId");

						b.HasIndex("UserId");

						b.ToTable("SitePermission");
					});

			modelBuilder.Entity("hedwig.Models.User", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd();

						b.Property<string>("FirstName")
											.IsRequired()
											.HasMaxLength(35);

						b.Property<string>("LastName")
											.IsRequired()
											.HasMaxLength(35);

						b.Property<string>("MiddleName")
											.HasMaxLength(35);

						b.Property<string>("Suffix")
											.HasMaxLength(10);

						b.HasKey("Id");

						b.ToTable("User");
					});

			modelBuilder.Entity("hedwig.Models.Child", b =>
					{
						b.HasOne("hedwig.Models.Family", "Family")
											.WithMany("Children")
											.HasForeignKey("FamilyId");
					});

			modelBuilder.Entity("hedwig.Models.Enrollment", b =>
					{
						b.HasOne("hedwig.Models.Child", "Child")
											.WithMany("Enrollments")
											.HasForeignKey("ChildId")
											.OnDelete(DeleteBehavior.Cascade);

						b.HasOne("hedwig.Models.Site", "Site")
											.WithMany("Enrollments")
											.HasForeignKey("SiteId")
											.OnDelete(DeleteBehavior.Cascade);
					});

			modelBuilder.Entity("hedwig.Models.FamilyDetermination", b =>
					{
						b.HasOne("hedwig.Models.Family", "Family")
											.WithMany("Determinations")
											.HasForeignKey("FamilyId")
											.OnDelete(DeleteBehavior.Cascade);
					});

			modelBuilder.Entity("hedwig.Models.Funding", b =>
					{
						b.HasOne("hedwig.Models.Enrollment", "Enrollment")
											.WithMany("Fundings")
											.HasForeignKey("EnrollmentId")
											.OnDelete(DeleteBehavior.Cascade);
					});

			modelBuilder.Entity("hedwig.Models.SitePermission", b =>
					{
						b.HasOne("hedwig.Models.Site", "Site")
											.WithMany()
											.HasForeignKey("SiteId")
											.OnDelete(DeleteBehavior.Cascade);

						b.HasOne("hedwig.Models.User", "User")
											.WithMany("SitePermissions")
											.HasForeignKey("UserId")
											.OnDelete(DeleteBehavior.Cascade);
					});
#pragma warning restore 612, 618
		}
	}
}
