// tslint:disable
// eslint-disable
/**
 * Hedwig API test
 * Prototype of REST API for Hedwig client 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Determination
 */
export interface Determination {
    /**
     * 
     * @type {number}
     * @memberof Determination
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Determination
     */
    numberOfPeople: number;
    /**
     * 
     * @type {number}
     * @memberof Determination
     */
    income: number;
    /**
     * 
     * @type {string}
     * @memberof Determination
     */
    determined?: string;
}

export function DeterminationFromJSON(json: any): Determination {
    return DeterminationFromJSONTyped(json, false);
}

export function DeterminationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Determination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'numberOfPeople': json['numberOfPeople'],
        'income': json['income'],
        'determined': !exists(json, 'determined') ? undefined : json['determined'],
    };
}

export function DeterminationToJSON(value?: Determination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'numberOfPeople': value.numberOfPeople,
        'income': value.income,
        'determined': value.determined,
    };
}


