// tslint:disable
// eslint-disable
/**
 * Hedwig API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Enrollment,
    EnrollmentFromJSON,
    EnrollmentFromJSONTyped,
    EnrollmentToJSON,
    FundingSource,
    FundingSourceFromJSON,
    FundingSourceFromJSONTyped,
    FundingSourceToJSON,
    FundingTime,
    FundingTimeFromJSON,
    FundingTimeFromJSONTyped,
    FundingTimeToJSON,
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface Funding
 */
export interface Funding {
    /**
     * 
     * @type {number}
     * @memberof Funding
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Funding
     */
    enrollmentId?: number;
    /**
     * 
     * @type {Enrollment}
     * @memberof Funding
     */
    enrollment?: Enrollment;
    /**
     * 
     * @type {FundingSource}
     * @memberof Funding
     */
    source?: FundingSource;
    /**
     * 
     * @type {FundingTime}
     * @memberof Funding
     */
    time?: FundingTime;
    /**
     * 
     * @type {number}
     * @memberof Funding
     */
    authorId?: number | null;
    /**
     * 
     * @type {User}
     * @memberof Funding
     */
    author?: User;
}

export function FundingFromJSON(json: any): Funding {
    return FundingFromJSONTyped(json, false);
}

export function FundingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Funding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'enrollmentId': !exists(json, 'enrollmentId') ? undefined : json['enrollmentId'],
        'enrollment': !exists(json, 'enrollment') ? undefined : EnrollmentFromJSON(json['enrollment']),
        'source': !exists(json, 'source') ? undefined : FundingSourceFromJSON(json['source']),
        'time': !exists(json, 'time') ? undefined : FundingTimeFromJSON(json['time']),
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
        'author': !exists(json, 'author') ? undefined : UserFromJSON(json['author']),
    };
}

export function FundingToJSON(value?: Funding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'enrollmentId': value.enrollmentId,
        'enrollment': EnrollmentToJSON(value.enrollment),
        'source': FundingSourceToJSON(value.source),
        'time': FundingTimeToJSON(value.time),
        'authorId': value.authorId,
        'author': UserToJSON(value.author),
    };
}


