// tslint:disable
// eslint-disable
/**
 * Hedwig API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum FundingTime {
    Full = 'Full',
    Part = 'Part'
}

export function FundingTimeFromJSON(json: any): FundingTime {
    return FundingTimeFromJSONTyped(json, false);
}

export function FundingTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FundingTime {
    return json as FundingTime;
}

export function FundingTimeToJSON(value?: FundingTime | null): any {
    return value as any;
}

