// tslint:disable
// eslint-disable
/**
 * Hedwig API test
 * Prototype of REST API for Hedwig client 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum FundingTime {
    FULL = 'FULL',
    PART = 'PART'
}

export function FundingTimeFromJSON(json: any): FundingTime {
    return FundingTimeFromJSONTyped(json, false);
}

export function FundingTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FundingTime {
    return json as FundingTime;
}

export function FundingTimeToJSON(value?: FundingTime | null): any {
    return value as any;
}

