// tslint:disable
// eslint-disable
/**
 * Hedwig API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrganizationReport,
    OrganizationReportFromJSON,
    OrganizationReportFromJSONTyped,
    OrganizationReportToJSON,
    Site,
    SiteFromJSON,
    SiteFromJSONTyped,
    SiteToJSON,
} from './';

/**
 * 
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {number}
     * @memberof Organization
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    name: string | null;
    /**
     * 
     * @type {Array<Site>}
     * @memberof Organization
     */
    sites?: Array<Site> | null;
    /**
     * 
     * @type {Array<OrganizationReport>}
     * @memberof Organization
     */
    reports?: Array<OrganizationReport> | null;
}

export function OrganizationFromJSON(json: any): Organization {
    return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'sites': !exists(json, 'sites') ? undefined : (json['sites'] === null ? null : (json['sites'] as Array<any>).map(SiteFromJSON)),
        'reports': !exists(json, 'reports') ? undefined : (json['reports'] === null ? null : (json['reports'] as Array<any>).map(OrganizationReportFromJSON)),
    };
}

export function OrganizationToJSON(value?: Organization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'sites': value.sites === undefined ? undefined : (value.sites === null ? null : (value.sites as Array<any>).map(SiteToJSON)),
        'reports': value.reports === undefined ? undefined : (value.reports === null ? null : (value.reports as Array<any>).map(OrganizationReportToJSON)),
    };
}


