#!/bin/sh
#
# To install, create a symlink from this file to `./git/hooks/pre-commit` by running something like:
# ln -s ../../hooks/pre-commit-docker-compose .git/hooks/pre-commit
# from the repository root

echo "Formatting frontend code (javascript, CSS, json)..."
./src/Hedwig/ClientApp/node_modules/.bin/prettier --single-quote --write "/home/node/app/src/**/*.{js,jsx,ts,tsx,json,css,scss}"

echo "Formatting backend code (C#)..."
dotnet format